# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf574bd69bd309acee2d08bd0b4a968f20722a4e630c5a4d8588ea42e46e1aa2e199d03317d506e6232aba5b0b26c2ec8372ae3ecb29df5d2e6d0c60a4952f6a

test:
  secret_key_base: e412c44ebc593f3512bd3ebea138d236e4d9a97a3a6063e0d5f958ce6b4c888baef07e73d4112cc80799732d8a8766540333d48e982e93ffbffd947049b55c7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>